package com.payutesting.utilities

object AvenuesParams{
	const val COMMAND = "command"
	const val ACCESS_CODE = "access_code"
	const val MERCHANT_ID = "merchant_id"
	const val ORDER_ID = "order_id"
	const val AMOUNT = "amount"
	const val CURRENCY = "currency"
	const val LANGUAGE = "language"
	const val ENC_VAL = "enc_val"
	const val REDIRECT_URL = "redirect_url"
	const val CANCEL_URL = "cancel_url"
	const val RSA_KEY_URL = "rsa_key_url"
	const val TRANS_URL = "trans_url"
	const val TRANS_DATA = "trans_data"
	const val PAYMENT_OPTION = "payment_option"
	const val BILLING_NAME = "billing_name"
	const val BILLING_ADDRESS = "billing_address"
	const val BILLING_CITY = "billing_city"
	const val BILLING_STATE = "billing_state"
	const val BILLING_ZIP = "billing_zip"
	const val BILLING_COUNTRY = "billing_country"
	const val BILLING_TEL = "billing_tel"
	const val BILLING_EMAIL = "billing_email"
	const val DELIVERY_NAME = "delivery_name"
	const val DELIVERY_ADDRESS = "delivery_address"
	const val DELIVERY_CITY = "delivery_city"
	const val DELIVERY_STATE = "delivery_state"
	const val DELIVERY_ZIP = "delivery_zip"
	const val DELIVERY_COUNTRY = "delivery_country"
	const val DELIVERY_TEL = "delivery_tel"
	const val MERCHANT_PARAM1 = "merchant_param1"
	const val MERCHANT_PARAM2 = "merchant_param2"
	const val MERCHANT_PARAM3 = "merchant_param3"
	const val MERCHANT_PARAM4 = "merchant_param4"
	const val MERCHANT_PARAM5 = "merchant_param5"
	const val PROMO_CODE = "promo_code"
	const val CUSTOMER_IDENTIFIER = "customer_identifier"

}